# Imagem oficial do PostgreSQL
FROM postgres:16

# Variáveis de ambiente básicas
ENV POSTGRES_DB=app_db
ENV POSTGRES_USER=app_user
ENV POSTGRES_PASSWORD=app_password

# Porta padrão do PostgreSQL
EXPOSE 5432

